version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=partxplorer
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/partxplorer
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=partxplorer
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_MAX_CONNECTIONS=10
      - DB_IDLE_TIMEOUT=30000
      - DB_CONNECTION_TIMEOUT=10000
      - DB_SSL=false
      - UPLOAD_DIR=uploads
      - MAX_UPLOAD_MB=25
    command: npm run dev
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend

volumes:
  db-data: